[package]
name = "tensors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tensors"
path = "src/lib.rs"

[[bin]]
name = "tensor"
path = "src/main.rs"

[dependencies]
pest = "2.6"
pest_derive = "2.6"
